"""qrp_atlas.indicators - 量化指标、特征与因子计算层。

本包基于 contracts 字段规则和调用方已准备的数据，计算市场宽度、市场风险、
个股趋势、系统 B 基础状态、横截面因子及其标准化结果，服务于市场监测、
复盘、策略、回测和研究分析。

Factor 是 Indicator 的专业子类型：本包负责生成可复用的客观事实、特征和
因子，不负责策略权重、交易授权、仓位、成交或未来收益评价。

依赖方向：contracts → indicators → strategies / backtest / api / frontend。

子模块：
    - market/         市场宽度与风险
    - stock/          个股趋势
    - system_b/       系统 B 基础状态检测
    - cross_section/  横截面算子、历史股票池、因子与中性化
    - service         对外组合入口
"""

# 指标元数据定义与注册表
from qrp_atlas.indicators.definitions import (
    IndicatorDefinition,
    IndicatorLayer,
    IndicatorScope,
    UpdateFrequency,
)
from qrp_atlas.indicators.registry import get_indicator, list_indicators
from qrp_atlas.indicators.parameterized import (
    IndicatorCalculationDefinition,
    IndicatorConflictError,
    IndicatorParameterBinding,
    IndicatorParameterSpec,
    IndicatorRequest,
    IndicatorRequestError,
    UnknownIndicatorError,
    bind_indicator_request,
    calculate_indicators,
    get_calculation_definition,
    indicator_output_fields,
    resolve_indicator_requests,
)

# 市场复合指标计算
from qrp_atlas.indicators.market import calculate_market_breadth, calculate_market_risk
from qrp_atlas.indicators.stock import (
    ASSET_RETURN,
    BENCHMARK_ID,
    BENCHMARK_RETURN,
    DIAGNOSTIC_CODE,
    RESIDUAL_CALCULATION_VERSION,
    RESIDUAL_OUTPUT_COLUMNS,
    RESIDUAL_RETURN,
    RESIDUAL_ZSCORE,
    ROLLING_ALPHA,
    ROLLING_BETA,
    ROLLING_R2,
    ResidualIndicatorError,
    ResidualIndicatorResult,
    calculate_market_residuals,
    calculate_stock_trend,
)
from qrp_atlas.indicators.system_b import (
    SystemBStateMachineError,
    calculate_system_b_2_0_states,
    detect_system_b_basic_state,
    detect_system_b_basic_state_from_prices,
)
from qrp_atlas.indicators.service import calculate_daily_market_snapshot
from qrp_atlas.indicators.m5 import (
    M5ObservationError,
    calculate_m5_observations,
    calculate_m5_raw_observations,
)

# 横截面指标、因子与研究基础
from qrp_atlas.indicators.cross_section import (
    CrossSectionFrameError,
    FACTOR_DEFINITIONS,
    FactorDefinition,
    FactorError,
    FactorParameterSpec,
    FactorRequest,
    FactorRequestError,
    HistoricalUniverseRequest,
    HistoricalUniverseSource,
    REQUIRED_CROSS_SECTION_COLUMNS,
    ResolvedFactorRequest,
    UnknownFactorError,
    apply_cross_section_operators,
    build_historical_universe,
    compute_amihud_illiquidity_factor,
    compute_average_traded_amount_factor,
    compute_average_turnover_factor,
    compute_distance_to_high_factor,
    compute_downside_volatility_factor,
    compute_high_low_range_volatility_factor,
    compute_intermediate_momentum_factor,
    compute_price_efficiency_factor,
    compute_price_volume_correlation_factor,
    compute_realized_volatility_factor,
    compute_relative_volume_factor,
    compute_rolling_max_drawdown_factor,
    compute_short_term_reversal_factor,
    compute_trend_r_squared_factor,
    compute_trend_slope_factor,
    compute_turnover_change_factor,
    compute_book_to_price_factor,
    compute_daily_basic_factor,
    compute_log_market_cap_factor,
    compute_momentum_factor,
    compute_roe_factor,
    cross_section_percentile_rank,
    cross_section_rank,
    cross_section_winsorize,
    cross_section_zscore,
    enforce_cross_section_primary_key,
    ensure_cross_section_frame,
    generate_factor_frame,
    NeutralizationError,
    neutralize_cross_section,
    neutralize_factor_frame,
    get_factor_definition,
    list_factors,
    normalize_asset_id,
    normalize_feature_columns,
    normalize_trade_date,
    normalize_trade_dates,
    process_cross_section,
    resolve_factor_requests,
    resolve_historical_universe,
    sort_cross_section_frame,
)

# 事件指标（业绩预告）
from qrp_atlas.indicators.events import (
    DIRECTION_SCORE_BY_FORECAST_TYPE,
    UNKNOWN_FORECAST_TYPE_DIRECTION,
    attach_earnings_forecast_indicators,
    compute_direction_score,
    compute_event_age,
    compute_event_window,
    compute_net_profit_midpoint,
    compute_net_profit_range,
    compute_profit_change_midpoint,
    compute_profit_change_range,
    map_forecast_type_direction,
)

__all__ = [
    # 元数据定义
    "IndicatorDefinition",
    "IndicatorLayer",
    "IndicatorScope",
    "UpdateFrequency",
    "get_indicator",
    "list_indicators",
    "IndicatorConflictError",
    "IndicatorCalculationDefinition",
    "IndicatorParameterBinding",
    "IndicatorParameterSpec",
    "IndicatorRequest",
    "IndicatorRequestError",
    "UnknownIndicatorError",
    "bind_indicator_request",
    "calculate_indicators",
    "get_calculation_definition",
    "indicator_output_fields",
    "resolve_indicator_requests",
    # 市场复合指标
    "calculate_market_breadth",
    "calculate_market_risk",
    "calculate_stock_trend",
    "calculate_market_residuals",
    "ResidualIndicatorError",
    "ResidualIndicatorResult",
    "RESIDUAL_OUTPUT_COLUMNS",
    "ROLLING_ALPHA",
    "ROLLING_BETA",
    "ROLLING_R2",
    "RESIDUAL_RETURN",
    "RESIDUAL_ZSCORE",
    "ASSET_RETURN",
    "BENCHMARK_RETURN",
    "BENCHMARK_ID",
    "DIAGNOSTIC_CODE",
    "RESIDUAL_CALCULATION_VERSION",
    "detect_system_b_basic_state",
    "detect_system_b_basic_state_from_prices",
    "SystemBStateMachineError",
    "calculate_system_b_2_0_states",
    "calculate_daily_market_snapshot",
    "M5ObservationError",
    "calculate_m5_observations",
    "calculate_m5_raw_observations",
    # 横截面指标与因子
    "CrossSectionFrameError",
    "FACTOR_DEFINITIONS",
    "FactorDefinition",
    "FactorError",
    "FactorParameterSpec",
    "FactorRequest",
    "FactorRequestError",
    "HistoricalUniverseRequest",
    "HistoricalUniverseSource",
    "REQUIRED_CROSS_SECTION_COLUMNS",
    "ResolvedFactorRequest",
    "UnknownFactorError",
    "apply_cross_section_operators",
    "build_historical_universe",
    "compute_amihud_illiquidity_factor",
    "compute_average_traded_amount_factor",
    "compute_average_turnover_factor",
    "compute_distance_to_high_factor",
    "compute_downside_volatility_factor",
    "compute_high_low_range_volatility_factor",
    "compute_intermediate_momentum_factor",
    "compute_price_efficiency_factor",
    "compute_price_volume_correlation_factor",
    "compute_realized_volatility_factor",
    "compute_relative_volume_factor",
    "compute_rolling_max_drawdown_factor",
    "compute_short_term_reversal_factor",
    "compute_trend_r_squared_factor",
    "compute_trend_slope_factor",
    "compute_turnover_change_factor",
    "compute_book_to_price_factor",
    "compute_daily_basic_factor",
    "compute_log_market_cap_factor",
    "compute_momentum_factor",
    "compute_roe_factor",
    "cross_section_percentile_rank",
    "cross_section_rank",
    "cross_section_winsorize",
    "cross_section_zscore",
    "enforce_cross_section_primary_key",
    "ensure_cross_section_frame",
    "generate_factor_frame",
    "NeutralizationError",
    "neutralize_cross_section",
    "neutralize_factor_frame",
    "get_factor_definition",
    "list_factors",
    "normalize_asset_id",
    "normalize_feature_columns",
    "normalize_trade_date",
    "normalize_trade_dates",
    "process_cross_section",
    "resolve_factor_requests",
    "resolve_historical_universe",
    "sort_cross_section_frame",
    "DIRECTION_SCORE_BY_FORECAST_TYPE",
    "UNKNOWN_FORECAST_TYPE_DIRECTION",
    "attach_earnings_forecast_indicators",
    "compute_direction_score",
    "compute_event_age",
    "compute_event_window",
    "compute_net_profit_midpoint",
    "compute_net_profit_range",
    "compute_profit_change_midpoint",
    "compute_profit_change_range",
    "map_forecast_type_direction",
]
