"""Generic backtest engine and optional strategy runtime adapters."""

from .engine import BacktestEngine
from .models import (
    BacktestConfig,
    BacktestResult,
    CostRule,
    EntryRule,
    ExitRule,
    PositionRule,
    Skipped,
    Trade,
)
from .exposure_data import prepare_cross_section_exposure_panel
from .factor_data import prepare_financial_factor_panel
from .residual_data import ResidualDataError, ResidualPanelPreparation, prepare_market_residual_panel
from .point_in_time import select_latest_available_records
from .pit_queries import (
    IndustryMembershipConflictError,
    query_earnings_forecast_as_of,
    query_financial_as_of,
    query_index_components_as_of,
    query_industry_as_of,
    summarize_index_components,
    to_earnings_forecast_event_frame,
)
from .portfolio import (
    PortfolioBacktestConfig,
    PortfolioBacktestEngine,
    PortfolioBacktestResult,
    PortfolioExecutionRule,
    PortfolioFill,
    PortfolioOrder,
    PortfolioSnapshot,
    PositionSnapshot,
    StrategyPortfolioBacktestRun,
    run_strategy_portfolio_backtest,
    strategy_decisions_to_target_weights,
)
from .runtime import StrategyBacktestRun, StrategyBacktestRuntime, prepare_strategy_data, run_strategy_backtest
from .research import (
    CrossSectionResearchError,
    CrossSectionResearchResult,
    ResidualResearchError,
    ResidualResearchResult,
    ResidualStrategyBacktestRun,
    TargetExposureResult,
    analyze_target_exposures,
    assign_factor_groups,
    compute_forward_returns,
    compute_group_returns,
    compute_information_coefficient,
    run_cross_section_research,
    run_market_residual_mean_reversion_backtest,
    run_residual_research,
    summarize_information_coefficient,
)

__all__ = [
    "BacktestConfig",
    "BacktestEngine",
    "BacktestResult",
    "CostRule",
    "EntryRule",
    "ExitRule",
    "PortfolioBacktestConfig",
    "PortfolioBacktestEngine",
    "PortfolioBacktestResult",
    "PortfolioExecutionRule",
    "PortfolioFill",
    "PortfolioOrder",
    "PortfolioSnapshot",
    "PositionRule",
    "PositionSnapshot",
    "Skipped",
    "StrategyBacktestRun",
    "StrategyBacktestRuntime",
    "StrategyPortfolioBacktestRun",
    "Trade",
    "IndustryMembershipConflictError",
    "prepare_cross_section_exposure_panel",
    "prepare_financial_factor_panel",
    "prepare_market_residual_panel",
    "ResidualDataError",
    "ResidualPanelPreparation",
    "prepare_strategy_data",
    "query_earnings_forecast_as_of",
    "query_financial_as_of",
    "query_index_components_as_of",
    "query_industry_as_of",
    "run_strategy_backtest",
    "run_strategy_portfolio_backtest",
    "select_latest_available_records",
    "summarize_index_components",
    "to_earnings_forecast_event_frame",
    "strategy_decisions_to_target_weights",
    "CrossSectionResearchError",
    "CrossSectionResearchResult",
    "TargetExposureResult",
    "analyze_target_exposures",
    "assign_factor_groups",
    "compute_forward_returns",
    "compute_group_returns",
    "compute_information_coefficient",
    "run_cross_section_research",
    "run_market_residual_mean_reversion_backtest",
    "run_residual_research",
    "ResidualResearchError",
    "ResidualResearchResult",
    "ResidualStrategyBacktestRun",
    "summarize_information_coefficient",
]
